version: '3'
services:
  app:
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - .:/briecheese
    working_dir: /briecheese
    ports:
      - 8000:8000
    depends_on:
      feature_points_position_db:
        condition: service_healthy

  feature_points_position_db:
    image: mysql:8.0
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: briecheese
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asis/Tokyo'
    ports:
      - 3306:3306
    healthcheck:
        test: mysqladmin ping -h 127.0.0.1 -u$$MYSQL_USER -p$$MYSQL_PASSWORD
